# Generated by Django 4.1.3 on 2022-12-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogurt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdata',
            name='dateOfbirth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cusdata',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cusdata',
            name='phone',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
