# Generated by Django 4.1.3 on 2022-12-03 00:04

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('yogurt', '0002_alter_cusdata_dateofbirth_alter_cusdata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdata',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31, unique=True),
        ),
    ]
