# Generated by Django 4.1.3 on 2022-12-04 21:06

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('yogurt', '0004_cusdata_last_check_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idCus', models.IntegerField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('checkInTime', models.CharField(blank=True, default='', max_length=30)),
                ('orderPrice', models.IntegerField(default=0)),
                ('coupon', models.IntegerField(default=0)),
                ('flag', models.IntegerField(default=0)),
            ],
        ),
    ]
