# Generated by Django 4.1.3 on 2022-12-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogurt', '0005_checkindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkindata',
            name='idCus',
            field=models.IntegerField(),
        ),
    ]
