# Generated by Django 4.1.3 on 2022-12-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogurt', '0006_alter_checkindata_idcus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkindata',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='checkindata',
            name='idCus',
            field=models.IntegerField(default=0),
        ),
    ]
