# Generated by Django 4.1.3 on 2022-12-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogurt', '0008_cusdata_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusdata',
            name='provider',
            field=models.CharField(default='T-Mobile', max_length=200),
        ),
    ]
