# Generated by Django 4.1.3 on 2022-12-01 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idProfile', models.AutoField(primary_key=True, serialize=False)),
                ('key_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=30)),
                ('last_login', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
